### ISSUE TITLE
ReferenceError: avd_converter is not defined

### ISSUE THREAD

**Issue by amandabourbois** [bodymovin/bodymovin-to-smil#1]
I get `ReferenceError: avd_converter is not defined` when attempting to run this. What would be the cause of this? I'm very new to node.js, so it's possible I may not be doing things correctly.

**Comment by eeropic** [comment]
Hey there,
Change that ’avd_converter’ to ’smil_converter’ and it should work. There’s just a typo in the readme that’s based on the original bm->AVD converter.

**Comment by amandabourbois** [comment]
That did it, thank you!

**Comment by bodymovin** [comment]
thanks for noticing!
I'll fix it
